# Generated by Django 5.1.4 on 2024-12-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_User', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('gestionnaire_stocks', 'Gestionnaire de Stocks'), ('gestionnaire_ventes', 'Gestionnaire de Ventes')], max_length=50)),
            ],
        ),
    ]
