# Generated by Django 5.1.4 on 2024-12-13 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_Vente', models.AutoField(primary_key=True, serialize=False)),
                ('dateVente', models.DateField()),
                ('totalVente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='DetailVente',
            fields=[
                ('id_DetailVente', models.AutoField(primary_key=True, serialize=False)),
                ('id_Medicaments', models.CharField(max_length=255)),
                ('quantiteVendu', models.IntegerField()),
                ('sousTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_Vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionVentes.vente')),
            ],
        ),
    ]
