# Generated by Django 5.1.4 on 2025-01-22 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionStocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_Vente', models.AutoField(primary_key=True, serialize=False)),
                ('dateVente', models.DateTimeField(default=django.utils.timezone.now)),
                ('totalVente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailVente',
            fields=[
                ('id_DetailVente', models.AutoField(primary_key=True, serialize=False)),
                ('quantiteVendu', models.IntegerField()),
                ('sousTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_Medicaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionStocks.medicament')),
                ('id_Vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='GestionVentes.vente')),
            ],
        ),
    ]
