# Generated by Django 5.2.3 on 2025-06-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVentes', '0002_medicament_ordonnance_and_more'),
    ]

    operations = [
    ]
