# Generated by Django 5.2.3 on 2025-06-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionVentes', '0003_fix_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='code_barres',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detailvente',
            name='id_Vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionVentes.vente'),
        ),
        migrations.AlterField(
            model_name='detailvente',
            name='quantiteVendu',
            field=models.PositiveIntegerField(),
        ),
    ]
