# Generated by Django 5.1.4 on 2025-01-08 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedicament',
            fields=[
                ('id_Categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Categorie', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('est_cachee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id_Medicament', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicament_images/')),
                ('est_vendu', models.BooleanField(default=False)),
                ('est_cachee', models.BooleanField(default=False)),
                ('id_Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionStocks.categoriemedicament')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commande', models.FloatField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('livrée', 'Livrée')], max_length=50)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionStocks.fournisseur')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionStocks.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_Stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('date_preemption', models.DateField(blank=True, null=True)),
                ('seuil_alerte', models.IntegerField()),
                ('medicament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionStocks.medicament')),
            ],
        ),
    ]
