# Generated by Django 5.1.4 on 2025-01-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='quantite_commander',
            new_name='quantite_commande',
        ),
        migrations.AddField(
            model_name='medicament',
            name='est_cachee',
            field=models.BooleanField(default=False),
        ),
    ]
