# Generated by Django 5.1.4 on 2025-01-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('peremption', 'Péremption'), ('stock', 'Stock')], default='stock', max_length=20),
        ),
    ]
