# Generated by Django 5.1.4 on 2025-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='est_vendu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
