# Generated by Django 5.1.4 on 2025-01-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStocks', '0002_alter_medicament_est_vendu_alter_medicament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
