# Generated by Django 5.1.4 on 2025-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionStocks', '0003_alter_medicament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/medicaments/'),
        ),
    ]
